"""max payment per round

Revision ID: 04888d4d06bc
Revises: 95d366d7a513
Create Date: 2025-01-08 20:33:25.168581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = '04888d4d06bc'
down_revision: Union[str, None] = '95d366d7a513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('useragentuserinvocations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('round_payments', sa.Integer(), nullable=False, server_default='1'))
        batch_op.drop_column('round_invocations')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('useragentuserinvocations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('round_invocations', sa.INTEGER(), nullable=False, server_default='0'))
        batch_op.drop_column('round_payments')

    # ### end Alembic commands ###
