"""user invocation limit

Revision ID: 165909213a37
Revises: 67388c995637
Create Date: 2025-01-02 13:42:06.326547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = '165909213a37'
down_revision: Union[str, None] = '67388c995637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useragentuserinvocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('round_invocations', sa.Integer(), nullable=False),
    sa.Column('payment_invocations', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('useragentuserinvocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_useragentuserinvocations_tg_user_id'), ['tg_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_useragentuserinvocations_user_agent_id'), ['user_agent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('useragentuserinvocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_useragentuserinvocations_user_agent_id'))
        batch_op.drop_index(batch_op.f('ix_useragentuserinvocations_tg_user_id'))

    op.drop_table('useragentuserinvocations')
    # ### end Alembic commands ###
