"""new emission

Revision ID: 1667a281a504
Revises: b3530171fb21
Create Date: 2025-02-21 10:27:49.200723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = '1667a281a504'
down_revision: Union[str, None] = 'b3530171fb21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('totalcycleemissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('total_staked', sa.Integer(), nullable=False),
    sa.Column('total_emitted_before', sa.Integer(), nullable=False),
    sa.Column('emission', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('totalcycleemissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_totalcycleemissions_day'), ['day'], unique=False)

    with op.batch_alter_table('useragent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_useragent_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_useragent_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('userstaking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userstaking_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userstaking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userstaking_created_at'))

    with op.batch_alter_table('useragent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_useragent_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_useragent_created_at'))

    with op.batch_alter_table('totalcycleemissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_totalcycleemissions_day'))

    op.drop_table('totalcycleemissions')
    # ### end Alembic commands ###
