"""player emissions

Revision ID: 18bea031ba18
Revises: e8eb8a40e41a
Create Date: 2025-01-17 22:34:11.697017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = '18bea031ba18'
down_revision: Union[str, None] = 'e8eb8a40e41a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playerweeklyemissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('emission', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playerweeklyemissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playerweeklyemissions_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_playerweeklyemissions_tg_user_id'), ['tg_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_playerweeklyemissions_user_agent_id'), ['user_agent_id'], unique=False)

    op.create_table('stakerweeklyemissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('staking_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('emission', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stakerweeklyemissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stakerweeklyemissions_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_stakerweeklyemissions_staking_id'), ['staking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stakerweeklyemissions_tg_user_id'), ['tg_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stakerweeklyemissions_user_agent_id'), ['user_agent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stakerweeklyemissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stakerweeklyemissions_user_agent_id'))
        batch_op.drop_index(batch_op.f('ix_stakerweeklyemissions_tg_user_id'))
        batch_op.drop_index(batch_op.f('ix_stakerweeklyemissions_staking_id'))
        batch_op.drop_index(batch_op.f('ix_stakerweeklyemissions_day'))

    op.drop_table('stakerweeklyemissions')
    with op.batch_alter_table('playerweeklyemissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playerweeklyemissions_user_agent_id'))
        batch_op.drop_index(batch_op.f('ix_playerweeklyemissions_tg_user_id'))
        batch_op.drop_index(batch_op.f('ix_playerweeklyemissions_day'))

    op.drop_table('playerweeklyemissions')
    # ### end Alembic commands ###
