"""tracable withdraw

Revision ID: 1d481db333cf
Revises: 602ce8f24ea4
Create Date: 2025-01-22 16:50:30.354056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = '1d481db333cf'
down_revision: Union[str, None] = '602ce8f24ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tguserwithdraw', schema=None) as batch_op:
        batch_op.alter_column('tx_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tguserwithdraw', schema=None) as batch_op:
        batch_op.alter_column('tx_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
