"""tracable payment

Revision ID: 1fea8c100a26
Revises: 7610a6ec3558
Create Date: 2025-01-20 13:37:02.028669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = '1fea8c100a26'
down_revision: Union[str, None] = '7610a6ec3558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tguserdeposit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approve_tx_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.alter_column('tx_hash',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tguserdeposit', schema=None) as batch_op:
        batch_op.alter_column('tx_hash',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
        batch_op.drop_column('approve_tx_hash')

    # ### end Alembic commands ###
