"""user notifications

Revision ID: 2b990ac6de5f
Revises: 18bea031ba18
Create Date: 2025-01-19 21:37:00.979393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = '2b990ac6de5f'
down_revision: Union[str, None] = '18bea031ba18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tguserdmchat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chat_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tguserdmchat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tguserdmchat_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tguserdmchat_tg_user_id'), ['tg_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tguserdmchat_user_agent_id'), ['user_agent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tguserdmchat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tguserdmchat_user_agent_id'))
        batch_op.drop_index(batch_op.f('ix_tguserdmchat_tg_user_id'))
        batch_op.drop_index(batch_op.f('ix_tguserdmchat_created_at'))

    op.drop_table('tguserdmchat')
    # ### end Alembic commands ###
