"""user referral

Revision ID: 441507680cc0
Revises: f9c3c8e083fb
Create Date: 2025-01-10 11:53:41.475935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = '441507680cc0'
down_revision: Union[str, None] = 'f9c3c8e083fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userreferrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('num_referrals', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('referred_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('userreferrals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userreferrals_tg_user_id'), ['tg_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userreferrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userreferrals_tg_user_id'))

    op.drop_table('userreferrals')
    # ### end Alembic commands ###
