"""record user withdraw

Revision ID: 526b2b4b9d44
Revises: d606c1bcb3c5
Create Date: 2025-01-03 16:11:57.444348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = '526b2b4b9d44'
down_revision: Union[str, None] = 'd606c1bcb3c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tguserwithdraw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('user_agent_round', sa.Integer(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tguserwithdraw', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tguserwithdraw_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tguserwithdraw_tg_user_id'), ['tg_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tguserwithdraw_user_agent_id'), ['user_agent_id'], unique=False)

    with op.batch_alter_table('useragentdata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('awe_token_staking', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_emissions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_income_shares', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('useragentdata', schema=None) as batch_op:
        batch_op.drop_column('total_income_shares')
        batch_op.drop_column('total_emissions')
        batch_op.drop_column('awe_token_staking')

    with op.batch_alter_table('tguserwithdraw', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tguserwithdraw_user_agent_id'))
        batch_op.drop_index(batch_op.f('ix_tguserwithdraw_tg_user_id'))
        batch_op.drop_index(batch_op.f('ix_tguserwithdraw_created_at'))

    op.drop_table('tguserwithdraw')
    # ### end Alembic commands ###
