"""tracable game pool charge

Revision ID: 5a67ce2dfe78
Revises: 1d481db333cf
Create Date: 2025-02-06 08:59:12.408838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5a67ce2dfe78'
down_revision: Union[str, None] = '1d481db333cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gamepoolcharge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approve_tx_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.alter_column('tx_hash',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gamepoolcharge', schema=None) as batch_op:
        batch_op.alter_column('tx_hash',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
        batch_op.drop_column('approve_tx_hash')

    # ### end Alembic commands ###
