"""new init

Revision ID: 5d5194b3150d
Revises:
Create Date: 2025-01-03 19:08:32.555625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = '5d5194b3150d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tgbotuserwallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phantom_session', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phantom_encryption_public_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tgbotuserwallet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tgbotuserwallet_tg_user_id'), ['tg_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tgbotuserwallet_user_agent_id'), ['user_agent_id'], unique=False)

    op.create_table('tgphantomusednonce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nonce', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nonce')
    )
    op.create_table('tguserdeposit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('user_agent_round', sa.Integer(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tguserdeposit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tguserdeposit_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tguserdeposit_tg_user_id'), ['tg_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tguserdeposit_user_agent_id'), ['user_agent_id'], unique=False)

    op.create_table('tguserwithdraw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('user_agent_round', sa.Integer(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tguserwithdraw', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tguserwithdraw_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tguserwithdraw_tg_user_id'), ['tg_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tguserwithdraw_user_agent_id'), ['user_agent_id'], unique=False)

    op.create_table('useragent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('staking_amount', sa.Integer(), nullable=True),
    sa.Column('tg_bot', awe.models.json_pydantic_field.JsonPydanticField(), nullable=True),
    sa.Column('awe_agent', awe.models.json_pydantic_field.JsonPydanticField(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('useragent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_useragent_user_address'), ['user_address'], unique=False)

    op.create_table('useragentstatsinvocationdailycounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('tool', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invocations', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('useragentstatsinvocationdailycounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_useragentstatsinvocationdailycounts_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_useragentstatsinvocationdailycounts_tool'), ['tool'], unique=False)
        batch_op.create_index(batch_op.f('ix_useragentstatsinvocationdailycounts_user_agent_id'), ['user_agent_id'], unique=False)

    op.create_table('useragentstatsinvocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('useragentstatsinvocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_useragentstatsinvocations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_useragentstatsinvocations_tg_user_id'), ['tg_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_useragentstatsinvocations_user_agent_id'), ['user_agent_id'], unique=False)

    op.create_table('useragentstatspaymentdailycounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('transactions', sa.Integer(), nullable=False),
    sa.Column('creator_amount', sa.Integer(), nullable=False),
    sa.Column('pool_amount', sa.Integer(), nullable=False),
    sa.Column('addresses', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('useragentstatspaymentdailycounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_useragentstatspaymentdailycounts_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_useragentstatspaymentdailycounts_user_agent_id'), ['user_agent_id'], unique=False)

    op.create_table('useragentstatstokentransferdailycounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('transactions', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('addresses', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('useragentstatstokentransferdailycounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_useragentstatstokentransferdailycounts_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_useragentstatstokentransferdailycounts_user_agent_id'), ['user_agent_id'], unique=False)

    op.create_table('useragentstatsuserdailycounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('users', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('useragentstatsuserdailycounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_useragentstatsuserdailycounts_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_useragentstatsuserdailycounts_user_agent_id'), ['user_agent_id'], unique=False)

    op.create_table('useragentuserinvocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('round_invocations', sa.Integer(), nullable=False),
    sa.Column('payment_invocations', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('useragentuserinvocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_useragentuserinvocations_tg_user_id'), ['tg_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_useragentuserinvocations_user_agent_id'), ['user_agent_id'], unique=False)

    op.create_table('userstaking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('release_tx_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('released_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('userstaking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userstaking_tg_user_id'), ['tg_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_userstaking_user_agent_id'), ['user_agent_id'], unique=False)

    op.create_table('useragentdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('awe_token_round_transferred', sa.Integer(), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False, server_default='1'),
    sa.Column('awe_token_quote', sa.Integer(), nullable=False),
    sa.Column('awe_token_staking', sa.Integer(), nullable=False),
    sa.Column('total_invocations', sa.Integer(), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('total_emissions', sa.Integer(), nullable=False),
    sa.Column('total_income_shares', sa.Integer(), nullable=False),
    sa.Column('awe_token_total_transferred', sa.Integer(), nullable=False),
    sa.Column('awe_token_total_transactions', sa.Integer(), nullable=False),
    sa.Column('awe_token_total_addresses', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_agent_id'], ['useragent.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_agent_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('useragentdata')
    with op.batch_alter_table('userstaking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userstaking_user_agent_id'))
        batch_op.drop_index(batch_op.f('ix_userstaking_tg_user_id'))

    op.drop_table('userstaking')
    with op.batch_alter_table('useragentuserinvocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_useragentuserinvocations_user_agent_id'))
        batch_op.drop_index(batch_op.f('ix_useragentuserinvocations_tg_user_id'))

    op.drop_table('useragentuserinvocations')
    with op.batch_alter_table('useragentstatsuserdailycounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_useragentstatsuserdailycounts_user_agent_id'))
        batch_op.drop_index(batch_op.f('ix_useragentstatsuserdailycounts_day'))

    op.drop_table('useragentstatsuserdailycounts')
    with op.batch_alter_table('useragentstatstokentransferdailycounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_useragentstatstokentransferdailycounts_user_agent_id'))
        batch_op.drop_index(batch_op.f('ix_useragentstatstokentransferdailycounts_day'))

    op.drop_table('useragentstatstokentransferdailycounts')
    with op.batch_alter_table('useragentstatspaymentdailycounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_useragentstatspaymentdailycounts_user_agent_id'))
        batch_op.drop_index(batch_op.f('ix_useragentstatspaymentdailycounts_day'))

    op.drop_table('useragentstatspaymentdailycounts')
    with op.batch_alter_table('useragentstatsinvocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_useragentstatsinvocations_user_agent_id'))
        batch_op.drop_index(batch_op.f('ix_useragentstatsinvocations_tg_user_id'))
        batch_op.drop_index(batch_op.f('ix_useragentstatsinvocations_created_at'))

    op.drop_table('useragentstatsinvocations')
    with op.batch_alter_table('useragentstatsinvocationdailycounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_useragentstatsinvocationdailycounts_user_agent_id'))
        batch_op.drop_index(batch_op.f('ix_useragentstatsinvocationdailycounts_tool'))
        batch_op.drop_index(batch_op.f('ix_useragentstatsinvocationdailycounts_day'))

    op.drop_table('useragentstatsinvocationdailycounts')
    with op.batch_alter_table('useragent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_useragent_user_address'))

    op.drop_table('useragent')
    with op.batch_alter_table('tguserwithdraw', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tguserwithdraw_user_agent_id'))
        batch_op.drop_index(batch_op.f('ix_tguserwithdraw_tg_user_id'))
        batch_op.drop_index(batch_op.f('ix_tguserwithdraw_created_at'))

    op.drop_table('tguserwithdraw')
    with op.batch_alter_table('tguserdeposit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tguserdeposit_user_agent_id'))
        batch_op.drop_index(batch_op.f('ix_tguserdeposit_tg_user_id'))
        batch_op.drop_index(batch_op.f('ix_tguserdeposit_created_at'))

    op.drop_table('tguserdeposit')
    op.drop_table('tgphantomusednonce')
    with op.batch_alter_table('tgbotuserwallet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tgbotuserwallet_user_agent_id'))
        batch_op.drop_index(batch_op.f('ix_tgbotuserwallet_tg_user_id'))

    op.drop_table('tgbotuserwallet')
    # ### end Alembic commands ###
