"""tracable agent refund

Revision ID: 5ebfb608f941
Revises: 274ad7f480c1
Create Date: 2025-02-07 07:59:24.339467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = '5ebfb608f941'
down_revision: Union[str, None] = '274ad7f480c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useragentrefund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('tx_last_valid_block_height', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('useragentrefund', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_useragentrefund_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_useragentrefund_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_useragentrefund_user_agent_id'), ['user_agent_id'], unique=False)

    with op.batch_alter_table('userstaking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_status', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_userstaking_release_status'), ['release_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userstaking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userstaking_release_status'))
        batch_op.drop_column('release_status')

    with op.batch_alter_table('useragentrefund', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_useragentrefund_user_agent_id'))
        batch_op.drop_index(batch_op.f('ix_useragentrefund_status'))
        batch_op.drop_index(batch_op.f('ix_useragentrefund_created_at'))

    op.drop_table('useragentrefund')
    # ### end Alembic commands ###
