"""round time

Revision ID: 602ce8f24ea4
Revises: 1fea8c100a26
Create Date: 2025-01-22 14:16:26.307994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = '602ce8f24ea4'
down_revision: Union[str, None] = '1fea8c100a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('useragentdata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_round_started_at', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('useragentdata', schema=None) as batch_op:
        batch_op.drop_column('current_round_started_at')

    # ### end Alembic commands ###
