"""return staking

Revision ID: 67388c995637
Revises: d6d5151b8cb3
Create Date: 2024-12-31 21:30:59.154299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe
from awe.settings import settings
from sqlmodel import Session, select
from awe.db import engine
from awe.models import UserAgent


# revision identifiers, used by Alembic.
revision: str = '67388c995637'
down_revision: Union[str, None] = 'd6d5151b8cb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('useragent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staking_amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.Integer(), nullable=True))

    # ### end Alembic commands ###
    with Session(engine) as session:
        statement = select(UserAgent)
        user_agents = session.exec(statement).all()
        for user_agent in user_agents:
            user_agent.staking_amount = settings.tn_agent_staking_amount
            session.add(user_agent)

        session.commit()

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('useragent', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('staking_amount')

    # ### end Alembic commands ###
