"""async user staking tx

Revision ID: 74c7205c156e
Revises: dd7d6ad0085e
Create Date: 2025-02-06 15:36:46.264151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = '74c7205c156e'
down_revision: Union[str, None] = 'dd7d6ad0085e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userstaking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tx_last_valid_block_height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_userstaking_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userstaking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userstaking_status'))
        batch_op.drop_column('status')
        batch_op.drop_column('tx_last_valid_block_height')

    # ### end Alembic commands ###
