"""tracable staking

Revision ID: 7610a6ec3558
Revises: 2b990ac6de5f
Create Date: 2025-01-20 12:55:51.509368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = '7610a6ec3558'
down_revision: Union[str, None] = '2b990ac6de5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userstaking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approve_tx_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.alter_column('tx_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userstaking', schema=None) as batch_op:
        batch_op.alter_column('tx_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('approve_tx_hash')

    # ### end Alembic commands ###
