"""user account withdraw

Revision ID: 78ac98dfed32
Revises: f6ba5c54db09
Create Date: 2025-02-08 21:48:52.008937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '78ac98dfed32'
down_revision: Union[str, None] = 'f6ba5c54db09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tguserwithdraw', schema=None) as batch_op:
        batch_op.drop_column('user_agent_round')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tguserwithdraw', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent_round', mysql.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
