"""agent data relations

Revision ID: 7e18b3dd118b
Revises: 391a5784e4d0
Create Date: 2024-12-19 23:16:01.532623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = '7e18b3dd118b'
down_revision: Union[str, None] = '391a5784e4d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('useragentdata', schema=None) as batch_op:
        batch_op.create_foreign_key("user_agent_with_data", 'useragent', ['user_agent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('useragentdata', schema=None) as batch_op:
        batch_op.drop_constraint("user_agent_with_data", type_='foreignkey')

    # ### end Alembic commands ###
