"""verify phantom wallet

Revision ID: 88b95c9b5f9d
Revises: 99ff8881ef99
Create Date: 2024-12-25 18:58:16.694269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = '88b95c9b5f9d'
down_revision: Union[str, None] = '99ff8881ef99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tgbotuserwallet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phantom_session', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('phantom_encryption_public_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.drop_column('session')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tgbotuserwallet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('phantom_encryption_public_key')
        batch_op.drop_column('phantom_session')

    # ### end Alembic commands ###
