"""agent account withdraw

Revision ID: 8948e373caa7
Revises: 78ac98dfed32
Create Date: 2025-02-09 12:36:49.828776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = '8948e373caa7'
down_revision: Union[str, None] = '78ac98dfed32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentaccountwithdraw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('tx_last_valid_block_height', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agentaccountwithdraw', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agentaccountwithdraw_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agentaccountwithdraw_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agentaccountwithdraw_user_agent_id'), ['user_agent_id'], unique=False)

    op.create_table('tguseragentreward',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tguseragentreward', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tguseragentreward_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tguseragentreward_round'), ['round'], unique=False)
        batch_op.create_index(batch_op.f('ix_tguseragentreward_tg_user_id'), ['tg_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tguseragentreward_user_agent_id'), ['user_agent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tguseragentreward', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tguseragentreward_user_agent_id'))
        batch_op.drop_index(batch_op.f('ix_tguseragentreward_tg_user_id'))
        batch_op.drop_index(batch_op.f('ix_tguseragentreward_round'))
        batch_op.drop_index(batch_op.f('ix_tguseragentreward_created_at'))

    op.drop_table('tguseragentreward')
    with op.batch_alter_table('agentaccountwithdraw', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agentaccountwithdraw_user_agent_id'))
        batch_op.drop_index(batch_op.f('ix_agentaccountwithdraw_status'))
        batch_op.drop_index(batch_op.f('ix_agentaccountwithdraw_created_at'))

    op.drop_table('agentaccountwithdraw')
    # ### end Alembic commands ###
