"""staking stats

Revision ID: 95d366d7a513
Revises: 5d5194b3150d
Create Date: 2025-01-03 22:39:33.833379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = '95d366d7a513'
down_revision: Union[str, None] = '5d5194b3150d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useragentstatsstakingdailycounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('in_amount', sa.Integer(), nullable=False),
    sa.Column('out_amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('useragentstatsstakingdailycounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_useragentstatsstakingdailycounts_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_useragentstatsstakingdailycounts_user_agent_id'), ['user_agent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('useragentstatsstakingdailycounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_useragentstatsstakingdailycounts_user_agent_id'))
        batch_op.drop_index(batch_op.f('ix_useragentstatsstakingdailycounts_day'))

    op.drop_table('useragentstatsstakingdailycounts')
    # ### end Alembic commands ###
