"""activate user referral

Revision ID: ac3bbe33745b
Revises: 441507680cc0
Create Date: 2025-01-10 14:35:56.494442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = 'ac3bbe33745b'
down_revision: Union[str, None] = '441507680cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userreferrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_activated_referrals', sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column('activated', sa.Boolean(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userreferrals', schema=None) as batch_op:
        batch_op.drop_column('activated')
        batch_op.drop_column('num_activated_referrals')

    # ### end Alembic commands ###
