"""int_referred_by

Revision ID: aed2c1074de6
Revises: ac3bbe33745b
Create Date: 2025-01-10 15:24:43.826537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = 'aed2c1074de6'
down_revision: Union[str, None] = 'ac3bbe33745b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userreferrals', schema=None) as batch_op:
        batch_op.alter_column('referred_by',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userreferrals', schema=None) as batch_op:
        batch_op.alter_column('referred_by',
               existing_type=sa.Integer(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)

    # ### end Alembic commands ###
