"""creator emissions

Revision ID: b19b5efa149b
Revises: 1667a281a504
Create Date: 2025-02-24 08:50:20.270915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = 'b19b5efa149b'
down_revision: Union[str, None] = '1667a281a504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creatorweeklyemissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('emission', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creatorweeklyemissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creatorweeklyemissions_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_creatorweeklyemissions_user_agent_id'), ['user_agent_id'], unique=False)

    op.create_table('stakerglobalweeklyemissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('staking_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('emission', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stakerglobalweeklyemissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stakerglobalweeklyemissions_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_stakerglobalweeklyemissions_staking_id'), ['staking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stakerglobalweeklyemissions_tg_user_id'), ['tg_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stakerglobalweeklyemissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stakerglobalweeklyemissions_tg_user_id'))
        batch_op.drop_index(batch_op.f('ix_stakerglobalweeklyemissions_staking_id'))
        batch_op.drop_index(batch_op.f('ix_stakerglobalweeklyemissions_day'))

    op.drop_table('stakerglobalweeklyemissions')
    with op.batch_alter_table('creatorweeklyemissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creatorweeklyemissions_user_agent_id'))
        batch_op.drop_index(batch_op.f('ix_creatorweeklyemissions_day'))

    op.drop_table('creatorweeklyemissions')
    # ### end Alembic commands ###
