"""global tg user wallet

Revision ID: b3530171fb21
Revises: d90ccab36fc0
Create Date: 2025-02-12 17:24:52.953395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b3530171fb21'
down_revision: Union[str, None] = 'd90ccab36fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tgbotuserwallet', schema=None) as batch_op:
        batch_op.drop_index('ix_tgbotuserwallet_user_agent_id')
        batch_op.drop_column('user_agent_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tgbotuserwallet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_index('ix_tgbotuserwallet_user_agent_id', ['user_agent_id'], unique=False)

    # ### end Alembic commands ###
