"""initial creation

Revision ID: d084fee4a187
Revises: 
Create Date: 2024-12-09 09:55:52.073979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = 'd084fee4a187'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tgbotuserwallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tgbotuserwallet_tg_user_id'), 'tgbotuserwallet', ['tg_user_id'], unique=False)
    op.create_index(op.f('ix_tgbotuserwallet_user_agent_id'), 'tgbotuserwallet', ['user_agent_id'], unique=False)
    op.create_table('useragent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tg_bot', awe.models.json_pydantic_field.JsonPydanticField(), nullable=True),
    sa.Column('awe_agent', awe.models.json_pydantic_field.JsonPydanticField(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('total_invocations', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_useragent_user_address'), 'useragent', ['user_address'], unique=False)
    op.create_table('useragentdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('awe_token_round_transferred', sa.Integer(), nullable=False),
    sa.Column('awe_token_total_transferred', sa.Integer(), nullable=False),
    sa.Column('awe_token_quote', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_agent_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('useragentdata')
    op.drop_index(op.f('ix_useragent_user_address'), table_name='useragent')
    op.drop_table('useragent')
    op.drop_index(op.f('ix_tgbotuserwallet_user_agent_id'), table_name='tgbotuserwallet')
    op.drop_index(op.f('ix_tgbotuserwallet_tg_user_id'), table_name='tgbotuserwallet')
    op.drop_table('tgbotuserwallet')
    # ### end Alembic commands ###
