"""release staking

Revision ID: d606c1bcb3c5
Revises: 35e3083dbc4a
Create Date: 2025-01-03 09:30:07.461969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = 'd606c1bcb3c5'
down_revision: Union[str, None] = '35e3083dbc4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userstaking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_tx_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userstaking', schema=None) as batch_op:
        batch_op.drop_column('release_tx_hash')

    # ### end Alembic commands ###
