"""user_price

Revision ID: d6d5151b8cb3
Revises: 88b95c9b5f9d
Create Date: 2024-12-26 10:11:55.933315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlmodel import Session, select
from awe.models import UserAgentData
from awe.db import engine

# revision identifiers, used by Alembic.
revision: str = 'd6d5151b8cb3'
down_revision: Union[str, None] = '88b95c9b5f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tguserdeposit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('user_agent_round', sa.Integer(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tguserdeposit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tguserdeposit_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tguserdeposit_tg_user_id'), ['tg_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tguserdeposit_user_agent_id'), ['user_agent_id'], unique=False)

    with op.batch_alter_table('useragentdata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_round', sa.Integer(), nullable=True))

    # ### end Alembic commands ###
    with Session(engine) as session:
        statement = select(UserAgentData)
        agent_data_list = session.exec(statement).all()
        for agent_data in agent_data_list:
            agent_data.current_round = 1
            session.add(agent_data)

        session.commit()



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('useragentdata', schema=None) as batch_op:
        batch_op.drop_column('current_round')

    with op.batch_alter_table('tguserdeposit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tguserdeposit_user_agent_id'))
        batch_op.drop_index(batch_op.f('ix_tguserdeposit_tg_user_id'))
        batch_op.drop_index(batch_op.f('ix_tguserdeposit_created_at'))

    op.drop_table('tguserdeposit')
    # ### end Alembic commands ###
