"""agent creation staking

Revision ID: d90ccab36fc0
Revises: 8948e373caa7
Create Date: 2025-02-10 15:48:17.193378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = 'd90ccab36fc0'
down_revision: Union[str, None] = '8948e373caa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useragentstaking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('approve_tx_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tx_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('tx_last_valid_block_height', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('useragentstaking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_useragentstaking_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_useragentstaking_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('useragentstaking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_useragentstaking_status'))
        batch_op.drop_index(batch_op.f('ix_useragentstaking_address'))

    op.drop_table('useragentstaking')
    # ### end Alembic commands ###
