"""tracable user withdraw

Revision ID: dd7d6ad0085e
Revises: 5a67ce2dfe78
Create Date: 2025-02-06 14:40:52.977728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = 'dd7d6ad0085e'
down_revision: Union[str, None] = '5a67ce2dfe78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tguserdeposit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tx_last_valid_block_height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_tguserdeposit_status'), ['status'], unique=False)

    with op.batch_alter_table('tguserwithdraw', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tx_last_valid_block_height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_tguserwithdraw_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tguserwithdraw', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tguserwithdraw_status'))
        batch_op.drop_column('status')
        batch_op.drop_column('tx_last_valid_block_height')

    with op.batch_alter_table('tguserdeposit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tguserdeposit_status'))
        batch_op.drop_column('status')
        batch_op.drop_column('tx_last_valid_block_height')

    # ### end Alembic commands ###
