"""weekly emission record

Revision ID: e8eb8a40e41a
Revises: 7c2599651a42
Create Date: 2025-01-17 09:56:33.104065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = 'e8eb8a40e41a'
down_revision: Union[str, None] = '7c2599651a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useragentweeklyemissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('emission', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('useragentweeklyemissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_useragentweeklyemissions_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_useragentweeklyemissions_user_agent_id'), ['user_agent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('useragentweeklyemissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_useragentweeklyemissions_user_agent_id'))
        batch_op.drop_index(batch_op.f('ix_useragentweeklyemissions_day'))

    op.drop_table('useragentweeklyemissions')
    # ### end Alembic commands ###
