"""tg user account deposit

Revision ID: f6ba5c54db09
Revises: 5ebfb608f941
Create Date: 2025-02-08 12:18:12.403589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f6ba5c54db09'
down_revision: Union[str, None] = '5ebfb608f941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awedeveloperaccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tguseraccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('rewards', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_user_id')
    )
    with op.batch_alter_table('tguseraccount', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tguseraccount_created_at'), ['created_at'], unique=False)

    op.create_table('tguseragentpayment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tguseragentpayment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tguseragentpayment_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tguseragentpayment_round'), ['round'], unique=False)
        batch_op.create_index(batch_op.f('ix_tguseragentpayment_tg_user_id'), ['tg_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tguseragentpayment_user_agent_id'), ['user_agent_id'], unique=False)

    with op.batch_alter_table('tguserdeposit', schema=None) as batch_op:
        batch_op.drop_column('user_agent_round')

    with op.batch_alter_table('useragentdata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('awe_token_creator_balance', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('useragentdata', schema=None) as batch_op:
        batch_op.drop_column('awe_token_creator_balance')

    with op.batch_alter_table('tguserdeposit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent_round', mysql.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('tguseragentpayment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tguseragentpayment_user_agent_id'))
        batch_op.drop_index(batch_op.f('ix_tguseragentpayment_tg_user_id'))
        batch_op.drop_index(batch_op.f('ix_tguseragentpayment_round'))
        batch_op.drop_index(batch_op.f('ix_tguseragentpayment_created_at'))

    op.drop_table('tguseragentpayment')
    with op.batch_alter_table('tguseraccount', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tguseraccount_created_at'))

    op.drop_table('tguseraccount')
    op.drop_table('awedeveloperaccount')
    # ### end Alembic commands ###
