"""game pool charge

Revision ID: f9c3c8e083fb
Revises: 04888d4d06bc
Create Date: 2025-01-09 23:18:34.394350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import awe


# revision identifiers, used by Alembic.
revision: str = 'f9c3c8e083fb'
down_revision: Union[str, None] = '04888d4d06bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamepoolcharge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_agent_id', sa.Integer(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gamepoolcharge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gamepoolcharge_user_agent_id'), ['user_agent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gamepoolcharge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gamepoolcharge_user_agent_id'))

    op.drop_table('gamepoolcharge')
    # ### end Alembic commands ###
